
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: 114433
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

